// <auto-generated />
using System;
using CoursePilotWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursePilotWebApp.Migrations
{
    [DbContext(typeof(CoursePilotDbContext))]
    [Migration("20231110103747_Initial migration")]
    partial class Initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursePilotWebApp.Models.Domain.Module", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HoursStudied")
                        .HasColumnType("int");

                    b.Property<int>("LastStudyDate")
                        .HasColumnType("int");

                    b.Property<int>("ModuleCode")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("credits")
                        .HasColumnType("int");

                    b.Property<int>("moduleName")
                        .HasColumnType("int");

                    b.Property<int>("selfStudyHoursPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("selfStudyHoursleft")
                        .HasColumnType("int");

                    b.Property<int>("startDate")
                        .HasColumnType("int");

                    b.Property<int>("weeklyClassHours")
                        .HasColumnType("int");

                    b.Property<int>("weeksInSem")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("CoursePilotWebApp.Models.Domain.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ModuleUser", b =>
                {
                    b.Property<Guid>("modulesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("usersID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("modulesID", "usersID");

                    b.HasIndex("usersID");

                    b.ToTable("ModuleUser");
                });

            modelBuilder.Entity("ModuleUser", b =>
                {
                    b.HasOne("CoursePilotWebApp.Models.Domain.Module", null)
                        .WithMany()
                        .HasForeignKey("modulesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursePilotWebApp.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("usersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
